### ISSUE TITLE
How to make variables?

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Paradise#10]
Hi there!

When continuing to overhaul the WildcardLisp files for my PR #9 (and possible other PRs), I found that there seem to already be lists, lambdas, and `let` statements. However, I am unsure as to how these are done.

- Firstly, how are lists created? Should I add a `list a b c ...` wildcard?
- Secondly, how are variables defined? It looks like you need to make a list with `let` as the first element, but I'm not sure.
- Thirdly, how are lambdas defined? Again, it looks like it is done with `lambda` as the first element of a list, but I'm not sure.

Maybe some documentation is necessary?

Thanks!

**Comment by microlith57** [comment]
I found out how lists work:
```
@( (1, 2, 3) ) -> 1,2,3
```
and I made some functions to handle them - wildcards for lists of children and siblings.
I also made a `map` wildcard:
```javascript
map: function (list, func) {
  if (typeof list === 'function') {
    list = list()
  }
  console.log(list);
  console.log(func);

  if (list instanceof Array) {
    return list.map(func)
  }
}
```

It doesn't seem to work, but I think that's a by-product of my misunderstanding of lambdas, not the actual `map` function. I made this command sequence:

```
create chair &
create table &
echo @( map siblings ( lambda id ( vessel id name ) ) )
```

Copyable: `create chair & create table & echo @( map siblings ( lambda id ( vessel id name ) ) )`

(using my `echo`, `map`, and `siblings` commands - you'll probably need [my repo](https://github.com/microlith57/Paradise) to reproduce this).

However, it fails with the error (where `[FILTERED]` is the directory I've cloned my repo to):
```
TypeError: input[1].reduce is not a function
    at [FILTERED]/desktop/server/core/wildcard.js:34:38
    at Array.map (<anonymous>)
    at map ([FILTERED]/desktop/server/core/wildcard.js:202:21)
    at interpretList ([FILTERED]/desktop/server/core/lisp.js:49:50)
    at interpret ([FILTERED]/desktop/server/core/lisp.js:56:14)
[obstructed by weird Blessed interference]/desktop/server/core/lisp.js:54:14)
```
There is more, but I had to type this manually because Blessed doesn't allow for text selection, and I didn't use the desktop client.

It would be great if you could offer any explanation as to how lambdas work.
Thanks!

**Comment by neauoire** [comment]
Hey :)
I'm working on something else today, and I want to review your PRs fully focused, 
I'll have a look at all of this tonight. 

I'm excited!

**Comment by microlith57** [comment]
Apologies about the comment about `map`. I got it to work:

```
create chair &
create table &
echo @( map siblings ( lambda (id) ( vessel id name ) ) )
```

Copyable: 'create chair & create table & echo @( map siblings ( lambda (id) ( vessel id name ) ) )'

I'll add some error checking and add documentation.

Still don't know how to use `let`.

**Comment by neauoire** [comment]
That's because `input[1]` is not an array. 
Reduce only works with arrays :) It would work on `input` tho :)

**Comment by neauoire** [comment]
It's best if we don't implement `let` to paradise.
I think I have neutered the let method in the lisp interpreter.

**Comment by microlith57** [comment]
OK! I assume this is because things like variables would have to persist somehow. I'll remove variables and functions from my TODO.md.
