### ISSUE TITLE
Desktop client forces export to .grid filetype

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Paradise#12]
Hi there!

I have discovered a bug (that I fixed when introducing YAML, but that is out of scope so I removed it) regarding file exports. It results in `.grid` being appended to all exported teapot files.

Specifically, when exporting a file, the following code runs: (desktop/sources/scripts/browser.js)

```javascript
101   this.export = function () {
102     dialog.showSaveDialog({ title: 'Save World', filters: [{ name: 'Teapot Format', extensions: ['teapot'] }] }, (fileName) => {
103       if (fileName === undefined) { return }
104       fileName = fileName.substr(-5, 5) != '.grid' ? fileName + '.grid' : fileName
105       fs.writeFileSync(fileName, paradise.export())
106     })
107   }
```

This function first shows a dialog (line `102`) with the only available extension being `.teapot`. This is fine, as Electron (I believe) will always output a filename from this that ends with `.teapot`.

However, line `104` then immediately appends `.grid` to the filename. Is this intended?
The bug here is either that `.grid` is appended in the first place, or that the `import` function does not accept `.grid` files.

A fix is available in PR #11

**Comment by neauoire** [comment]
Cheers!
