### ISSUE TITLE
Crashes caused by @( query )

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Paradise#14]
Steps:
```
create button
enter button
trigger say You said: @( query )
leave
say @( query )
```
Upon `say @( query )`, Paradise hangs.

This is because when evaluating the WildcardLISP, Paradise evaluates `@( query )` to `say @( query )`, which causes recursion, and would eventually crash.

**Comment by microlith57** [comment]
Suggested fix: move the LISP interpreter into another thread and watch its resources. If it takes too long or uses too much CPU/memory, stop it and raise an error.

**Comment by neauoire** [comment]
I'll check if a function is passed instead of a string, and block it there.

**Comment by microlith57** [comment]
That's probably a better idea!
