### ISSUE TITLE
Missing image for `learn` action

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Paradise#25]
Reproduction steps:
- `learn to learn`
- Observe broken image

Suggested fix:

1. Add `learn.png` image that is one of the following:
    - A copy of `default.png` (as in [this branch](https://github.com/microlith57/Paradise/tree/hotfix/learn-image-happy))
    - A copy of `help.png` (as in [this branch](https://github.com/microlith57/Paradise/tree/hotfix/learn-image-sad))
    - Entirely new
2. (optional) Test for lack of image, and automatically use `default.png` instead.

I have some partial solutions to this problem, and would be happy to open a PR for whichever image you prefer. I am also working on an automatic `default.png` fallback.

**Comment by neauoire** [comment]
Can you add help.png as learn.png in your latest PR? :)

**Comment by microlith57** [comment]
Will do!

**Comment by microlith57** [comment]
Fixed both steps with the above 2 PRs!

**Comment by neauoire** [comment]
perfect :)
