### ISSUE TITLE
Client ID does not persist

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Paradise#29]
When saving the world, the ID of the client is not saved.

Steps:

1. Run Paradise Desktop client
2. `create teapot`
3. `become teapot`
4. Close the desktop client
5. Reopen the desktop client
6. You are now the ghost - you should be the chair

Suggested fix:
- Store the Client ID with the world.
- When multiplayer is implemented, store this as an object `{client: ID}`

**Comment by neauoire** [comment]
Fixing that now

**Comment by microlith57** [comment]
This is a very neat solution! The only unfortunate thing is that the data is not persisted in the CLI, but then and again, _nothing_ is persisted in the CLI, so that is a matter for another issue.
