### ISSUE TITLE
[Suggestion] Potential Multiplayer Implementation

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Paradise#30]
Possible steps for a multiplayer implementation:

- Store 'possessed' vessels in client data / cookies, like the world is in the desktop client
- Move away from using `paradise.ghost()` and `paradise.client` and instead use client list, `host`, etc.
  - How to do this if the client controls possession?
  - Do we need these methods at all?
- Use methods like `vessel.is_host()`
- Potentially when a client joins a world, they immediately `become` a newly created vessel
  - This vessel could be a copy of a template vessel, potentially existing as a paradox of itself at ID 0.
  - When the template is copied, the new vessel is moved inside its owner (the library by default).
  - Before this, its program is run (if present)
  - This would allow for unlimited creation of arbitrary clients, and would still allow for configuration / customisation
  - Potentially need some method of auto-deletion when a client leaves a large server

Edit: change `Store clients and associated vessels in world files (re: #29)` to `Store 'possessed' vessels in client data / cookies, like the world is in the desktop client`

**Comment by TangentFoxy** [comment]
I forgot to reply here when I made it, but I did actually make a multiplayer version of this. It's got differences, and isn't as complete, but there is a kind of start: https://github.com/TangentFoxy/Arcadia

I probably forgot to mention it because I considered it unworthy of attention, but since this is still here and I haven't worked on it in a long time, I figured I should at least point to someone having begun an implementation of similar.

**Comment by TangentFoxy** [comment]
Also, this is very much OLD code and bad, but before I ever heard of Paradise, I started a similar project - the idea of an interactive creative world: https://github.com/TangentFoxy/Realms

Sorry if this is considered spam, but I felt it worth sharing, if nothing else to get ideas flowing.

**Comment by neauoire** [comment]
Nice work TangentFoxy :)

We've been implementing Paradise in Uxn, and planning on using Nilix's 9P implementation for multiplayer :)
The project development has moved to https://git.sr.ht/~rabbits/parade/

**Comment by TangentFoxy** [comment]
Thank you. Where can I read about the 9P implementation? (I'm not good at low level stuff at all, so I want to see an overview if I can.)

**Comment by neauoire** [comment]
Have a look at this :)
https://nilfm.cc/git/xrxs/about/
