### ISSUE TITLE
Passive notes do not allow code

### ISSUE THREAD

**Issue by TangentFoxy** [hundredrabbits/Paradise#42]
Not sure if intentional or not, but I noticed on the web version just now that `pass Hello (host)` just prints that raw instead of doing my intent, having it welcome the possessed vessel by name.

**Comment by neauoire** [comment]
The pass active sets a passive note that is displayed when the vessel is inside your inventory. Here's a bit of code that demonstrates how this works, you can just paste this inside paradise.

```
create an mirror & enter the mirror & pass hello (guest) & leave & take the mirror &
create an map & enter the map & pass at (guest:parent) & leave & take the map &
create a doll & enter the doll & pass is a (host) & leave & take the doll
```

**Comment by TangentFoxy** [comment]
So when the web version is showing text at the bottom of the screen, that is just it informing you of the current parent vessel's passive note? Looks like programs are also displayed there. Maybe there should be formatting to indicate these.

How much is the web version expected to differ from the version on itch.io? I noticed the `inspect` action is gone as well.

**Comment by neauoire** [comment]
it's very different, the web version is a branch of the concept hoping for it to become the next build, but it's not there yet. It's a kind of prototype atm. I will make the note/program/pass display more obvious too.

**Comment by TangentFoxy** [comment]
Awesome! :D
