### ISSUE TITLE
Unknown actions always return You said "undefined"

### ISSUE THREAD

**Issue by TangentFoxy** [hundredrabbits/Paradise#43]
On the web version, when attempting to do something the interpreter doesn't understand, it just gives you `You said "undefined"`

Is this meant to say what the user input? Making talking to the environment some sort of default action? Or have things gone more wrong than expected?

**Comment by neauoire** [comment]
Oh, will fix this in morning :) Nice catch

**Comment by TangentFoxy** [comment]
This is also happening on any attempts to use `use`. Caught that later while offline so didn't say it sooner. ^^;

**Comment by neauoire** [comment]
I've fixed the undefined error, the idea is that I use paradise as a toolkit for all sorts of things you would use a lisp repl for. So if you type `(add 5 6)`, it will result in `You said "11"`.

### Use

`use` seems to be working for me

```
create a house & enter the house & program create a dog & leave & use the house
```

**Comment by TangentFoxy** [comment]
> the idea is that I use paradise as a toolkit for all sorts of things you would use a lisp repl for

Love that. Is there a function reference or getting started written anywhere? I'm new to lisp and this implementation, trying to learn it.

Re: `use` Unsure what I was doing wrong before. If I find specific replicable problem I will report it then. Thanks!

**Comment by neauoire** [comment]
There isn't much docs, but the [library source](https://github.com/hundredrabbits/Paradise/blob/master/web/scripts/lain.library.js) is pretty self explanatory :) If you have any question, let me know! I love talking about this stuff

**Comment by TangentFoxy** [comment]
Thank you very much. What would be the best way to approach you to ask questions about Lain specifically?

**Comment by neauoire** [comment]
Here's good, or just on mastodon if you have an account. I'm online if I'm awake :)

**Comment by TangentFoxy** [comment]
Had myself a little journey to find it (GitHub profile -> xxiivv.com -> wiki.xxiivv.com -> Twitter profile -> mastro profile), maybe adding an entry to Oscean would be a good idea? (I mean, if it's there I didn't find it, searched mastodon and that didn't help.)

Anyhow thanks again, and *crosses her fingers* I'm about to start testing a personal project inspired by Paradise so wish me luck.

**Comment by neauoire** [comment]
Paradise's lisp language is the same as the one on Oscean, its page is [here](https://wiki.xxiivv.com/Lain). Other good way to mess with it is with [Ronin](https://github.com/hundredrabbits/ronin).
