### ISSUE TITLE
`Inventory` command doesn't seem to work

### ISSUE THREAD

**Issue by microlith57** [hundredrabbits/Paradise#8]
Specifications:

- Running from latest source (on [my fork](https://github.com/microlith57/Paradise))
- OS: Ubuntu 18.04
- Running using CLI and Desktop

Issue description:
When I type `inventory`, an 'unknown action' error displays. This occurs with both CLI and Desktop.
Furthermore, using the default world (with a map), no inventory UI appears.

I have noticed that, despite the historical addition (via PR) of such a command, no `inventory.js` file exists. Furthermore, no inventory UI code seems to exist either.

A terminal-cast of the CLI issue is available [here](https://asciinema.org/a/eNyiFFRsOkUcF0TkTDweODeer).

I am currently in the process of attempting to recreate the missing command.

**Comment by microlith57** [comment]
The `inventory` command is now re-created. However, the UI element is not.

**Comment by neauoire** [comment]
Fixed with your latest PR :)
